### ISSUE TITLE
Using socket.io + nanoexpress on the same port?

### ISSUE THREAD

**Issue by supertiger1234** [nanoexpress/nanoexpress#103]
Is this even possible with nanoexpress?

On normal express, it was possible like this:
```js
var app = require('express')();
var http = require('http').createServer(app);
var io = require('socket.io')(http);

http.listen(3000, () => {
  console.log('listening on *:3000');
});
```
Thanks.

**Comment by dalisoft** [comment]
Hi @supertiger1234 

I don’t know as i am did not tested, but nanoexpress supports websocket out-of-the-box. 
I always prefer native websocket over socket.io and recommend to you too. 
There in examples folder has some examples, see and experiment. 
I hope you will find what you searching, if there any bug within library, i happy to help, if you want additional feature for cost, then please contact to me via telegram with @dalisoft username and we’ll talk about it more.
