### ISSUE TITLE
ws handler will parse invalid JSON strings without a try catch block causing server to crash on malformed inputs

### ISSUE THREAD

**Issue by kran6a** [nanoexpress/nanoexpress#106]
The bug is located in /src/handler/ws.js

The code fragment that causes the issue is this:
```
if (options.schema) {
        if (typeof message === 'string') {
          if (message.indexOf('[') === 0 || message.indexOf('{') === 0) {
            if (message.indexOf('[object') === -1) {
              message = JSON.parse(message);
            }
          }
        }
```

The code will attempt to JSON.parse() a string like `{keyWithoutQuotes:stringValueWithoutQuotes}` which is an invalid JSON object causing JSON.parse() to throw

**Comment by dalisoft** [comment]
Set {schema: false} and code do not try parse message
