### ISSUE TITLE
Route cannot be reused with different path

### ISSUE THREAD

**Issue by yarsky-tgz** [nanoexpress/nanoexpress#12]
We found such hackish solution for now (`oldRoute` is function which configures router):

```javascript
const router = new Route();
app.use('/auth/api', router);
oldRoute(router);
app.use('/', router);
oldRoute(router);
```

waiting for better solution

**Comment by dnohr** [comment]
Hi @dalisoft ,

Sorry for the late reply. I just reinstalled the libraries now to verify it, and with a fresh install, I'm still getting the same or similar issue.

Tested with the following code:
`
const nanoexpress = require('nanoexpress-pro/cjs');
const staticServe = require('nanoexpress-pro/cjs/static');
const app = nanoexpress();
app.use(staticServe(__dirname + '/public'));
app.get('/', (req, res) => { return res.send({ status: 'ok' }); });
app.listen(6006);
`

Try to put two different images in "public/" and a different one in "public/img", but with the same name. Seems like there can only be one static file with the same name.

Thanks.

**Comment by dalisoft** [comment]
@dnohr Please comment in another issue thread and well continue discussion

**Comment by dalisoft** [comment]
@yarsky-tgz Hi.
Currently solution is using `connect` as workaround, but may impact performance.
Route in `nanoexpress` isn't designed to use more than once, it's possible to fix it, but performance will drops and becomes like `connect middleware + nanoexpress` performance.

Try like this

```js
const router = connect();

// Now it's like Express API, exactly isn't working nanoexpress Layers anymore
// and `async` functions doesn't work like nanoexpress and WebSocket doesn't supports
router.get('/', (req, res) => {
res.send();
});

app.use('/auth/api', router);
app.use('/', router);
```

Thanks to @mrauhu for this solution

**Comment by dalisoft** [comment]
Hi @yarsky-tgz 

Please try `nanoexpress@6.x` aka `next` version.
I hope it will work for your case, i got it working on some routes at cost of `5%` performance drop, no i think it's not a lot of loss.

**Comment by dalisoft** [comment]
It's works on **nanoexpress** v8 release and seems enough stable as i'm used this on production, works fine
