### ISSUE TITLE
SSE implementation

### ISSUE THREAD

**Issue by kran6a** [nanoexpress/nanoexpress#165]
### Is your feature request related to a problem? Please describe
No

### Describe the solution you'd like
SSE is a technology that allows the server to broadcast a stream of events to the clients subscribed to a specific endpoint. Is is like an unidirectional websocket connection without the extra overhead of continously pinging the server to prevent the browser from closing the ws connection.

In order to create a SSE endpoint you need to enable TCP_NODELAY on the underlying socket since you will be pushing events through the same socket without closing the connection and by default they are buffered until the buffer reach max capacity and it is flushed. Currently nanoexpress responses do not expose the raw socket so SSE endpoints are not easy to implement.

A clear and concise description of what you want to happen. Add any considered drawbacks.
* Option 1: implement sse without a middleware just like websocket endpoints so we can create and use a sse endpoint like this:
``` javascript
const clients = app.sse('/events/:channel', config, middleware); //Config could contain an ajv JSON schema and headers to be able to support CORS middleware may reject the connection before it is handled by the sse implementation (for example the user did not privide the correct authorization header)
clients.broadcast('channel 1', {id: 0, event: 'message', data: 'hello world'});
```

* Option 2: expose the raw socket so people can create their own middlewares.
``` javascript
res.socket.setNoDelay(true) //Works in express but res.socket is undefined in nanoexpress
```

* Option 3: create a custom nanoexpress middleware so we can do
``` javascript
app.get('/events', {}, sseMiddleware, async (req, res)=>{}); //Option 1 is preferred over this since the handler will just add the response to an array to be able to broadcast events later.
```

Option 1 has no drawbacks and do not conflict with the existing nanoexpress methods.
Option 2 has no drawbacks but since socket is a common word someone might be already doing ```res.socket = "something"```
Option 3 the drawback of not having a broadcast method so you have to implement broadcasting yourself, also you need keep track of the clients that join and disconnect.

### Describe alternatives you've considered
Since my node servers are under nginx I have considered running sse endpoints on a separate express server but that increases the architectural complexity.

### Teachability, Documentation, Adoption, Migration Strategy
This is a good-looking and very simple implementation of a sse middleware in express: https://www.npmjs.com/package/sse-broadcast

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by dalisoft** [comment]
@kran6a I will look into this in next month (maybe in April), but i think it's not possible, i'll try

**Comment by dalisoft** [comment]
Hi @kran6a.

I tried to implement this, but seems it's not possible due of two reasons
- Methods are changed, but library is old
- uWebSockets.js (core of nanoexpress) is releasing HTTP instance after response, so memory usage is low.

See my trying experiment https://github.com/nanoexpress/nanoexpress/blob/master/examples/sse.js, you welcome to try and add support.

Thanks for trying out my framework.

**Comment by dalisoft** [comment]
No, it’s not fixed, it’s closed, huh
