### ISSUE TITLE
Can't set required field for ajv schema validation

### ISSUE THREAD

**Issue by hellovietduc** [nanoexpress/nanoexpress#168]
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Minimal reproducible repo

Link here

### Current Behavior

Suppose I have a request schema like this.

```typescript
const requestSchema: Schema = {
  query: {
    type: 'object',
    properties: {
      url: {
        type: 'string',
      },
    },
    required: ['url'],
  },
  ...
}
```

Setting the `required` field causes an error because the `SchemaValue` interface doesn't accept `string[]`, while it is [a valid syntax](https://ajv.js.org/json-schema.html#required) in Ajv.

### Expected behavior/code

Make `SchemaValue` accept `string[]`.

### Environment

- Node/npm version: [Node 12.16.0/npm 6.13.4]
- OS: [MacOS Big Sur 11.2.2]
- TypeScript: 4.2.3

### Possible Solution

```typescript
interface SchemaValue {
    [key: string]: string | string[] | SchemaValue;
  }
```

### Additional context/Screenshots

Add any other context about the problem here. If applicable, add screenshots to help explain.

### Note

- **Project is provided as-is without any support nor warranty**
- **If this issue not related to this project and exists on [core](https://github.com/uNetworking/uWebSockets.js) of this project, please close issue or not open**

**Comment by dalisoft** [comment]
@hellovietduc Hi and thanks for trying out.

Did you try change code to this?

```diff
const requestSchema: Schema = {
  query: {
    type: 'object',
    properties: {
      url: {
        type: 'string',
+     required: true
      },
    },
  },
  ...
}
```
