### ISSUE TITLE
RegExp paths for Routes?

### ISSUE THREAD

**Issue by AqilCont** [nanoexpress/nanoexpress#181]
## Feature Request
Can there be support for regular expression paths? I wanted to just copy over some code I had from express:
```js
app.get(/\/[^.]+\.html/, (req, res) => ... );
```
but I get this error, and I'm guessing you only expect string paths because of it:
```
d:/projects/help-mee/node_modules/nanoexpress/src/Route.js:109
    const fetchUrl = path.indexOf('*') !== -1 || path.indexOf(':') !== -1;
                          ^
TypeError: path.indexOf is not a function
    at Route._prepareMethod (d:/projects/help-mee/node_modules/nanoexpress/src/Route.js:109:27)
    at App.exposeAppMethod [as get] (d:/projects/help-mee/node_modules/nanoexpress/src/App.js:218:44)
```

### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Describe alternatives you've considered

I've considered just looping over every html file and making a separate route for it, but this is tedious, adds a ton of startup time and cpu on app initialize, and makes the whole app laggier. I am still forced to use it, but if you can implement this, I would really appreciate it!

**Comment by AqilCont** [comment]
I love this library, since it provides a really nice api wrapper for something I found a bit tough to use, with nice websocket support, and a lot of ease of use, mixed in with extremely good performance. Thanks for making and maintaining this awesome library!!!!

**Comment by dalisoft** [comment]
I’d think it is possible, but performance will be reduced and i do not want it. 
Please check out https://github.com/jesusvilla/natural for better route functionality and that library also free. 

Thank you for good kind of words. Wish you all the best.
