### ISSUE TITLE
Any way to wait for server closed?

### ISSUE THREAD

**Issue by howesteve** [nanoexpress/nanoexpress#231]
Hello, this is more of a doubt. 

So when I call this:
```js
// ...
app.listen(3000))
```
.. a promise is returned, and even if I wait for it:
```js
await app.listen(3000))
```
the next line is executed immediately.

My answer is, how can I wait until the server is stopped to finish closing other resources? 
```js
try {
  //...
  await app.listen(3000))
  // ==> should be waiting here somehow until server stops listening; e.g.
  await app.closed() 
} finally (e) {
  // cleaning up resources
  databasePool.close()
  app.close()
}
```
Thanks

**Comment by dalisoft** [comment]
Hi @howesteve 
Thank you for asking these questions, but it's not bug.

- There no `app.closed()` method
- `app.listen()` async/promise works properly, tested
- `app.close()` method code is [here](https://github.com/nanoexpress/nanoexpress/blob/master/src/App.js#L196)
