### ISSUE TITLE
cannot find module Route

### ISSUE THREAD

**Issue by mustard-mh** [nanoexpress/nanoexpress#235]
## Bug Report

use route feature then  run `node index.js` throw error: Cannot find module '.../nanoexpress/src/Route'
> $projectDict/node_modules/nanoexpress/src/Route.js is exist

(What exactly [PRO PRO Slim version](https://nanoexpress.js.org/routes/route) mean?)

### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Minimal reproducible repo

```javascript
// file: index.js
const nanoexpress = require('nanoexpress')
const Route = require('nanoexpress/src/Route')
const app = nanoexpress()

const testRoute = new Route()
app.use('/test', testRoute)
testRoute.get('/', async () => 'hello')

app.listen(3000).then().catch(e => console.error)
```

### Current Behavior

failed to run project

### Expected behavior/code

service start with route

### Environment

- node -v: `v16.2.0`
- OS: macOS Monterey 12.0 Beta

**Comment by dalisoft** [comment]
Hi @mustard-mh 

Thank you for trying out nanoexpress and reporting bugs or any questions related to documentation and it's improves documentation base.
I am updated documentation.

Try this
```diff
- const nanoexpress = require('nanoexpress')
+ const nanoexpress = require('nanoexpress/cjs')
- const Route = require('nanoexpress/src/Route')
+ const Route = require('nanoexpress/cjs/Route')
const app = nanoexpress()

const testRoute = new Route()
app.use('/test', testRoute)
testRoute.get('/', async () => 'hello')

- app.listen(3000).then().catch(e => console.error)
+ app.listen(3000).then().catch(e => console.error(e))
```

I hope this helps you

---

About **PRO and PRO Slim**, before has been three versions. I am removed simple version and made **PRO** version as **FREE** in hope of community supports me by code contribution, financial or documentation/tests improvements.
Seems works, but very slow, but good peoples like you helps project grow by reporting project.

Now only one version - **nanoexpress** itself, before known as **PRO**
