### ISSUE TITLE
More of the framework needs type declarations

### ISSUE THREAD

**Issue by ohmree** [nanoexpress/nanoexpress#247]
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Is your feature request related to a problem? Please describe

I'm trying to set up a basic app using the `Route` class but there aren't any type declarations for it.
For example, in the following snippet `Route` is of type `any` and my editor warns me about missing declarations for `nanoexpress/cjs/Route.js`.
```ts
import Route from 'nanoexpress/cjs/Route.js';
```

### Describe the solution you'd like

I'd like to have proper autocompletion and get warned whenever I do something I'm not supposed to do (type-wise), that's only possible if nanoexpress is rewritten in typescript or if type declarations are added for the rest of the library (and not just the main `nanoexpress` function).

### Describe alternatives you've considered

I've started going through the code and writing my own `.d.ts` files but figuring out the expected types of things (for example the various options that can be passed to some functions) has proven to be difficult, since I'm not the one who wrote the code and don't know how these objects are meant to be used very well.

### Teachability, Documentation, Adoption, Migration Strategy

If I understand it correctly all users will be able to benefit from a better editor experience, even if they don't use typescript for their own code.

P.S. thanks for making this, it looks really nice and I'd hate to have to switch libraries because of missing types.

**Comment by dalisoft** [comment]
I currently little bush, but I’ll do this as soon as I’ll get free time

**Comment by dalisoft** [comment]
There has declaration, but needs for improvements. Any PR welcome but there none available.
