### ISSUE TITLE
Needs a better structure

### ISSUE THREAD

**Issue by ohmree** [nanoexpress/nanoexpress#248]
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Is your feature request related to a problem? Please describe

Right now you have to reference source files directly when importing anything that isn't in the main `nanoexpress` import, and (more annoyingly) the import path depends on whether you're using commonjs or esm (when using typescript and targeting `esnext` or when using native esm).
This is how it looks right now:
```ts
// I'm okay with this...
import nanoexpress from 'nanoexpress';
// ...but not with this.
import Route from 'nanoexpress/cjs/Route.js';
// This is how the import would look like if I were targeting native esm:
// import Route from 'nanoexpress/src/Route.js';
```
Additionally, you can't do things like:
```ts
import nanoexpress, { Route } from 'nanoexpress';
const route = new Route(...);
```
Or
```ts
import nanoexpress from 'nanoexpress';
const route = new nanoexpress.Route(...);
```

### Describe the solution you'd like

I'd like for `src/nanoexpress.js` to export everything (for example the `Route` class), while still default-exporting the `nanoexpress` function.
Another thing that's maybe worth considering is also having stuff like `Route` be properties on the default-exported `nanoexpress` function (similarly to how it works in express), so they can be used like `nanoexpress.Route`, but that's definitely optional and I'm not even sure it's a good idea.

### Describe alternatives you've considered

Just using nanoexpress as-is, that's what I'm currently trying to do.

### Teachability, Documentation, Adoption, Migration Strategy

It shouldn't be very different to how it's used nowadays so changing the docs would probably be trivial.
If anything, it'll be easier to use since the import path will be be the same regardless of the module system you use/target.

I might be able to work on this but I'll have to learn a bit about exports first since I've never worked on a node library before.

**Comment by dalisoft** [comment]
I welcome any PR with changes related to this as well as more test coverages help project better. 
Currently on my projects i am using native uWebSockets.js, fiber (golang) so I spend less time improving this project. 
but great companies supporting me with great apps/services so i should do improve as they trusted me as Open Source author

**Comment by ohmree** [comment]
Fair enough, I might make a contribution then.

Thanks for the reply!

**Comment by dalisoft** [comment]
As no PR related to this issue - it’s not issue, just your wishes
