### ISSUE TITLE
NanoExpress can't write remove headers

### ISSUE THREAD

**Issue by gotshadowbantempaccount** [nanoexpress/nanoexpress#251]
Try to add headers in nanoExpress

    res.removeHeader('Content-Type');
    res.removeHeader('uWebSockets');
    res.setHeader('Content-Type', 'image/jpg');

But got now 2 headers and old one was never remove any way why its add me application/json

    Connection: close
    Content-Length: 2470
    Content-Type: image/jpg
    Content-Type: application/json

And now get error on my image:

And or image got
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

```
app.use(bodyParser({ json: true,limit: '5mb'}));
app.use( expressSession({
```

**Comment by dalisoft** [comment]
- You can’t remove uWebSockets
- You not using official bodyParser plugin
- You using the code wrong
- There no reproducible repository

**Comment by gotshadowbantempaccount** [comment]
```
/* Bodyparser -  https://github.com/nanoexpress/middlewares/tree/master/packages/body-parser */
const bodyParser = require('@nanoexpress/middleware-body-parser/cjs'); // from nano
```

`const expressSession = require('express-session'); <!---  this is the issue use before body parser from express and was crazzy many issues then switch to to: nanoexpress/middleware-body-parser  and now see that need use correct session tooo `
___

When read documents or on other pages is say is compatibility middleware so my mistake just maybe next time need think that * mean actually something 

Express-compatible middleware* layer
https://nanoexpress.js.org/

Tested Express/Connect like Middlewares
​body-parser (yes, if you don't want built-in) <<<<--- **where its say have to use nanoexpress/middleware-body-parse**
​express-fileupload​ 
​express-cors​
​express-jwt​
​express-session​
​express-graphql​
​passport

**Comment by gotshadowbantempaccount** [comment]
Do some test now and can confirm that session module generate thus bug:

ON main page link to session module is: https://github.com/expressjs/session

Same with: body-parser (yes, if you don't want built-in)  -->>  https://github.com/expressjs/body-parser

Should be: https://github.com/nanoexpress/middlewares/tree/master/packages/body-parser

Also don't see session modlevere form nano


```
app.use(
	  expressSession({
	    name: 'SESSSSS',
			store: MongoStore.create({
				mongoUrl: 'mongodb://127.0.0.1',
		    autoRemove: 'interval',
		    autoRemoveInterval: 190, // min
		    dbName: 'XXX'
		  }),
	    secret: 'DDDDDDDDD',
	    rolling: true,
	    resave: true,
	    saveUninitialized: false,
	    cookie: {
	      sameSite: false, //'strict'
	      secure: false,
	      maxAge: 6 * 30 * 24 * 60 * 60 * 1000,
	      httpOnly: true
	    },
	    logErrors: true
	  })
	);
```

**Comment by gotshadowbantempaccount** [comment]
@dalisoft  found source of error in

cjs/nanoexpress.js  line 2013

res.setHeader('Content-Type', 'application/json');

after comment it it stop adding application/json

on print error varible got:


`TypeError: res._implicitHeader is not a function  express-session\index.js:276:15)`

**Comment by dalisoft** [comment]
Seems it’s up to you. I checked on latest stable with passportjs and worked for me fine.

**Comment by dalisoft** [comment]
I’ll look into this issue next week or in next two week

**Comment by gotshadowbantempaccount** [comment]
actually found some commit interesting

 Fix https missing _implicitHeader function for express-session 
https://github.com/wapplr/wapplr-authentication/commit/a253e4d8ab99dfe3cf9a5bb269a9b9843c2cf09a

__
and more:
https://github.com/nginx/unit/issues/240

The compression module uses the _implicitHeader function, which exists in the original http module. However, I see that this function was removed here:

Also fix for compression module:

Replace calls to undocumented _implicitHeader, which is not present in http2, with the actual code of that method.
https://github.com/expressjs/compression/pull/155

__

I think this is some compatibility issue  on nanoewebpage its say This library **does not support HTTP2!** but this internal function are used only by HTTP2.
__
So rather than fix all this modules that can break maybe just add to core nanoexpress that fix auto many modules

```
if (!res._implicitHeader){
            res._implicitHeader = function () {
                console.log("[WAPPLR-AUTHENTICATION]", "http2 fix for express-session _implicitHeader");
                if (!res._header && !res.headersSent) {
                    res.writeHead(res.statusCode)
                }
            }
        }
```

**Comment by krishnaTORQUE** [comment]
I am also facing the same issue

**Comment by dalisoft** [comment]
Oh, yes, this is known-bug

**Comment by dalisoft** [comment]
The fact that any express or other frameworks doing wrong way, the correct way is always pushing header as duplicate

**Comment by dalisoft** [comment]
@gotshadowbantempaccount Please give us example minimal reproducible repo

@akhmadiy Please look into this issue too as soon as you can get
