### ISSUE TITLE
Is a nice pice of code but you can't sell it

### ISSUE THREAD

**Issue by gotshadowbantempaccount** [nanoexpress/nanoexpress#252]
## Feature Request
- missing benchmarks on main page ( this guy do it right ) http://gwan.com
**Missing info on main page**
Performance improvement by ~25%
Try to call EXPERIMENTAL_FASTCALL=1 node server.js
- missing information on main page say that is base uWebSockets
- also benchmark link from homepage https://nanoexpress.js.org/benchmark ?? missing where is graphs

A clear and concise description of what the problem is. Ex. I have an issue when [...]

### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

**Comment by dalisoft** [comment]
Hi @gotshadowbantempaccount 

Thank you a lot for notices, i appreciate any PR
