### ISSUE TITLE
Response and request .pipe() method seem bugged

### ISSUE THREAD

**Issue by kran6a** [nanoexpress/nanoexpress#265]
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Current Behavior
res.pipe() expects  `callback: (pipe: Readable) => void, size?: number, compressed?: boolean`
The callback gives me a Readable stream instead of a Writable so that I can stream data to the client
req.pipe() is defined on the interface but if called it throws `req.pipe is not a function`
A clear and concise description of what the problem is. Ex. I have an issue when [...]

### Expected Behavior
res.pipe() should allow to pipe a readable stream to the client
req.pipe() should be pipeable into a writable stream or the method should be removed from the interface

### Describe alternatives you've considered
Writing the response in chunks by attaching a listener to the readable stream and writing each chunk as it is read.

**Comment by dalisoft** [comment]
@kran6a Thank you for issue, can you please check it, it is fixed or still issue for you?
