### ISSUE TITLE
Allow getting IP address of machine accessing the server

### ISSUE THREAD

**Issue by javaarchive** [nanoexpress/nanoexpress#275]
### Is you/your team sponsoring this project

- [ ] Yes
- [X] No

### Is your feature request related to a problem? Please describe

I'm writing a ratelimiter that rate limits by ip but I hit a road block while trying to find the ip of the person requesting the resource. 

### Describe the solution you'd like

`getRemoteIPv4` and `getRemoteIPv6` or a similar api on the request object. According to uwebsockets.js docs because this project appears to be using it, we can get [the IPV6](https://github.com/uNetworking/uWebSockets.js/issues/460) address of a client in the request object so this should be easy as adding a file in `request-proto`.

### Describe alternatives you've considered

In production I don't actually need to think about this problem as a reverse proxy will pass the real ip as a header. 

### Teachability, Documentation, Adoption, Migration Strategy

Should be able to be documented similar to other request methods. 

### Other stuff
Since I need to exersice good coding style, I might just try doing my first legitimate PR on this

**Comment by dalisoft** [comment]
Hey @javaarchive!

Thank you for interest in nanoexpress

Try `req.getIP()` or `req.getProxiedIP()` and see it works or not for you

**Comment by javaarchive** [comment]
Oh, my bad I wasn't looking in the right place and there indeed is a method to get the requester ip of a request.
