### ISSUE TITLE
Getting Buffer in request.body

### ISSUE THREAD

**Issue by dougg0k** [nanoexpress/nanoexpress#304]
Hi, 

I'm getting a Buffer in the `request.body`, when I tried to add `body-parser` with `app.use(bodyParser.json());`, I get the error `stream.on is not a function` and a message `the key 'message' was not present`.

Right now the only way is to `JSON.parse(buffer.toString())` which are probably slowing down a bit given the parse.

I also tried `@nanoexpress/middleware-body-parser` and it's giving wrong typescript types and applying it to `use`, maybe it wasn't been updated.

Updated: 
Well, though very minimal given a simple body, `JSON PARSE: 0.085ms`

**Comment by dalisoft** [comment]
Can you describe issue with much more realistic example where and why does not work and i try fix or you can create PR for fix.

For using `body` nanoexpress expects `POST/PUT` with body for performance reason and reduce CPU/memory where it's does not need :)
