### ISSUE TITLE
Cut a new release with uwebsockets.js dependency

### ISSUE THREAD

**Issue by izelnakri** [nanoexpress/nanoexpress#324]
### Minimal reproducible repo

https://github.com/izelnakri/memoria/runs/4296814176?check_suite_focus=true#step:6:1205

### Current Behavior

On a dockerized CI environment npm cannot fetch the "uWebSockets.js" npm library, the library has become completely downcased

### Possible Solution

Cut a new release with "uwebsockets.js" dependency instead of "uWebSockets.js".

**Comment by dalisoft** [comment]
Seems you’re using either old version of nanoexpress or wrong version of uWS. 
please check this or submit PR with correct solution. 

Thank you

**Comment by izelnakri** [comment]
Please read the bug report better this time, I use the latest nanoexpress:

https://github.com/nanoexpress/nanoexpress/blob/master/package.json#L54

Thank you

**Comment by dalisoft** [comment]
@izelnakri Please check version on docker build and latest nanoexpress version is differs.
`uWebSockets.js@19.2.0' is not in this registry` error whereas nanoexpress uses v19.5.0, any questions?
I use in docker images too my nanoexpress, it works flawlessly

**Comment by izelnakri** [comment]
Yea error seems to be odd, I updated few internal pkgs and now I dont see it. However the npm error did tell me me all deps have to be all lower-case. 

Also is it ideal to have websocket.js version as a github link in production? This npm package could simply ship with the local dependency?

**Comment by dalisoft** [comment]
No, it will be better to use `zip` or `tar.gz` as on `Docker` will not be required `git` dependency and can reduce build image size up-to 25% which is huge for 100+ images on production environments

**Comment by izelnakri** [comment]
so let me get this right, you think a github link dependency thus a fragile build instructions are better because it reduces docker image sizes. I'm also curious where you got that 25% from, git dependency isn't that big and I had issues previously running nanoexpress on alpine actually, one has to get that very smooth first before advocating for docker image sizes.
