### ISSUE TITLE
Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.

### ISSUE THREAD

**Issue by dougg0k** [nanoexpress/nanoexpress#326]
![Screenshot from 2021-11-26 15-16-12](https://user-images.githubusercontent.com/10801221/143618840-23b9bb17-e225-4099-b596-b988cadac47b.png)

**Comment by dalisoft** [comment]
@dougg0k Thank you but I currently don’t have enough time for tracking this bug or error handling but PR with solutions are welcome

**Comment by dougg0k** [comment]
It's fine, same, no time available, I had to refactor to HyperExpress. They also have a solution built-in for a json body issue that I also had reported before. https://github.com/nanoexpress/nanoexpress/issues/304 

Plus they seem to have all up-to-date, like latest uWebsockets versions. 

Thanks for taking the time to create the lib though.

**Comment by dalisoft** [comment]
As you found another library i think i can close this PR

@akhmadiy Can you look to this issue for investage why it's happens?
@dougg0k Can you please give us example minimal repo for reproduce issue?
