### ISSUE TITLE
v5.2.3 includes "semantic-release" in dependencies

### ISSUE THREAD

**Issue by izelnakri** [nanoexpress/nanoexpress#385]
Hi there,

v5.2.3 includes `semantic-release` v19.0.2 in its dependencies, could you move it to devDependencies? Also, it fetches many files that aren't needed in an npm release, if you could clean them up with package.json `"files": ["$includedFolder/*"]` I'd appreciate.

I'm also bit confused with the `@next` tag that is release 9 months ago, it doesn seem to receive updates while v5 receives updates. Could you explain the difference between `next` tag and the `current` tag for `nanoexpress`?

**Comment by dalisoft** [comment]
@izelnakri 
Hello and thank you for interesting.
Yep, that's issue, can you please create PR for fixing this case? I would appreciate that.

About `@next` release, first it was plan fix bugs by reports but no reports nor interests got, seems users does not use really `nanoexpress`.

Almost 80% codebase for **next** was ported from PRO Ultimate for blazing fast performance and unbeatable stability (even compared to express in some cases)

**Comment by izelnakri** [comment]
Hi @dalisoft , I actually wanted to create a PR then wasn't sure which branch to branch off from since master doesnt seem to be v5.2.3. Would be great if you set up a release process. 

I understand you might get busy from time to time and have difficulties managing the balance, this issue isn't urgent but would be great the earlier its done and the project gets improved constantly just like all the tools we use. Don't give up on improvements/perfection over the long period of time, despite counter influences there might be, I wish you a good day!

There is a reason I chose nanoexress over express after more than a decade of node.js experience, thats more important than the npm download charts, popularity comes with adoption/conviction, however improvements needed to be made to keep what you've worked on better, we dont have responsibility for each other but if you want more people to use the software and existing ones to not leave, you'll need to maintain it ;)

**Comment by dalisoft** [comment]
Hi @izelnakri 
I fixed bug which `semantic-release` dependency was containing in production builds, sorry, i did not noticed that before and now it's fixed.
Please check and let me know
