### ISSUE TITLE
Problems with websocket

### ISSUE THREAD

**Issue by FerLuisxd** [nanoexpress/nanoexpress#46]
So basically I am trying to reproduce the basic example found in the [docs](https://nanoexpress.js.org/websocket#basic-example) with no luck 
This is my server code: 
```
const nanoexpress = require('nanoexpress-pro/cjs')

const app = nanoexpress();

app.ws('/', (req, ws) => {
  console.log('Connected');

  ws.on('message', (message) => {
    console.log('Message received', message);
  });
});

app.listen(4000);
```

And this is my client code:
``` 
var ws = new WebSocket('ws://localhost:4000'); 

ws.onopen = function () { 
  ws.send("hello!"); 
}

ws.onmessage = function(msg) { 
console.log('msg',msg)
  if(msg.data instanceof Blob) { 
    processBlob(msg.data);
  } else {
    processText(msg.data);
  }
}
```
When we execute the client code the server will crash:
![image](https://user-images.githubusercontent.com/29811965/85418881-fca8be00-b536-11ea-8a7e-7d92f7443c6e.png)

Any idea why?

**Comment by dalisoft** [comment]
Hi

Thanks for using nanoexpress, but please read [about new rules](https://github.com/nanoexpress/nanoexpress/issues/108) and do these steps

1. Create repo which presents minimal function/issue
2. Use external temporarily DB (Heroku MongoDB?) [if exists]
3. Replace entire snippet/part-of-code into link to your prepared repo

If you cannot these steps, this issue will be closed without any futher discussion and fixes

_Even better, i recommend you post on StackOverflow as it's not really shows bug, just like why it doesn't work_

I hope you understand me
Thanks

Regards,
Davlik

**Comment by dalisoft** [comment]
No response, no test repo. I'll closing this according to new rules

**Comment by ceddybi** [comment]
@dalisoft i think @FerLuisxd provided a valid example, i've actually faced the same issue with latest nanoexpress,

mine is now `TypeError: Cannot set property 'rawPath' of undefined`

Something you can look into, instead of just closing it

**Comment by dalisoft** [comment]
@ceddybi Thanks for let me know and thanks for interesting. Reopening issue and i'll fix it as soon as possible.

Happy new year!
Regards,
Davlik

**Comment by dalisoft** [comment]
@ceddybi I just tested and it works.

<details>
<summary>Screenshot</summary>

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/3511344/103269968-c57d0300-49d8-11eb-9a78-b335357679fa.png">

</details>

**Comment by dalisoft** [comment]
@FerLuisxd @ceddybi Please try using `nanoexpress` package, not `nanoexpress-pro` as new updates are pushed to `nanoexpress` package.

**Comment by ceddybi** [comment]
@dalisoft Yes I can confirm that it is working, I previously had old `v2.0.0`, I just updated to the latest version, and it works now

**Comment by dalisoft** [comment]
Thanks for testing and glad it is working. 

Have a nice day. 

Regards, 
Davlik
