### ISSUE TITLE
Invalid access of discarded

### ISSUE THREAD

**Issue by gabrielcursino** [nanoexpress/nanoexpress#575]
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Minimal reproducible repo

[Link here](https://github.com/gabrielcursino/nanoexpress-error)

### Current Behavior

A canceled request crashes the service

### Expected behavior/code

Canceled requests should not throw errors and crash the service

### Environment

- Node/npm version: Node 16/npm 8
- OS: Windows 11

### Additional context/Screenshots

Add any other context about the problem here. If applicable, add screenshots to help explain.

### Note

- **Project is provided as-is without any support nor warranty**
- **If this issue not related to this project and exists on [core](https://github.com/uNetworking/uWebSockets.js) of this project, please close issue or not open**

**Comment by Najsar** [comment]
add

```
res.onAborted(() => {
  return false;
});
```

**Comment by gabrielcursino** [comment]
@Najsar unfortunately the error persists

```javascript
import nanoexpress from 'nanoexpress';

const app = nanoexpress();

app

.get('/test', async (req, res) => {
  req.onAborted(() => false);

  res.onAborted(() => false);

  await new Promise(resolve => setTimeout(() => resolve(), 5000));

  return res.send('success');
});

app.listen(3000);
```
or
```javascript
import nanoexpress from 'nanoexpress';

const app = nanoexpress();

app

.get('/test', async (req, res) => {
  req.onAborted(() => res.send('error'));

  res.onAborted(() => res.send('error'));

  await new Promise(resolve => setTimeout(() => resolve(), 5000));

  return res.send('success');
});

app.listen(3000);
```
not works
