### ISSUE TITLE
`res.status` No effect in setErrorHandler function

### ISSUE THREAD

**Issue by blueway** [nanoexpress/nanoexpress#63]
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Minimal reproducible repo

```typescript
import nanoexpress from 'nanoexpress-pro';

const app = nanoexpress();

app.setErrorHandler((err, req, res) => {
  res.status(500)   // here not working ,the response status code will be 200
  res.end('error handled: ' + err.message);
});
app.get('/bar', async (req, res) => {
  throw new Error('Something was wrong in GET /bar');
  // eslint-disable-next-line no-unreachable
  res.send({ status: 'success' });
});

app.listen(4000);
```

### Current Behavior

A clear and concise description of the behavior.

### Expected behavior/code

A clear and concise description of what you expected to happen (or code).

### Environment

- Node/npm version:  node 12.18.2
- OS:  ubuntu
- Addinational Info: _type here_

### Additional context/Screenshots

Add any other context about the problem here. If applicable, add screenshots to help explain.

### Note

- **Project is provided as-is without any support nor warranty**
- **If this issue not related to this project and exists on [core](https://github.com/uNetworking/uWebSockets.js) of this project, please close issue or not open**

**Comment by dalisoft** [comment]
You should read docs and rules, but you didn’t read both.

**Comment by blueway** [comment]
sorry ,I've read the docs, but I don't know why it doesn't work

**Comment by dalisoft** [comment]
Hi @blueway 

Please fill missing fields such as "Current Behavior", "Excepted behavior", etc.
Would be nice to have screenshots too

**Comment by dalisoft** [comment]
@blueway 

Try 
```diff
import nanoexpress from 'nanoexpress-pro';

const app = nanoexpress();

app.setErrorHandler((err, req, res) => {
  res.status(500)   // here not working ,the response status code will be 200
+  res.send('error handled: ' + err.message);
-  res.end('error handled: ' + err.message);
});
app.get('/bar', async (req, res) => {
  throw new Error('Something was wrong in GET /bar');
  // eslint-disable-next-line no-unreachable
  res.send({ status: 'success' });
});

app.listen(4000);
```

**Comment by FM77-knde** [comment]
I can confirm this issue still exists (v2.4.4) and there is a bug in the implementation of the errorhandler, it sends a header premature of the processing of the configured errorhandler and prevents setting a custom statuscode and proper continuation.

In Route handler:
`            const handleError = (err) => {
              isAborted = true;

              **// this prevents processing the custom code in error-handler -> needs to be placed after next if-block!
              res.writeHeader(
                'Content-Type',
                'application/json; charset=utf-8'
              );**

              if (_config._errorHandler) {
                console.log('### call _errorHandler');
                return _config._errorHandler(err, req, res);
              }

              res.status(err.status || err.code || 400, true);
              res.writeStatus(res.statusCode);

              res.end(
                `{"error":"${typeof err === 'string' ? err : err.message}"}`
              );
              return res;
            };`

**Comment by dalisoft** [comment]
@FM77-knde Thanks, then i'll check these part of code

https://github.com/nanoexpress/nanoexpress/blob/96813ee82b788eb9eca0114fcf471dc189faeec2/src/Route.js#L359-L379

And fix this as soon as i can

**Comment by dalisoft** [comment]
@FM77-knde @blueway Please check, issue was fixed or still exists?
