### ISSUE TITLE
Issue with loadtest

### ISSUE THREAD

**Issue by mrddter** [nanoexpress/nanoexpress#64]
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### Minimal reproducible repo

https://github.com/mrddter/evaluation-nanoexpress

### Current Behavior

Hi I'm evaluating some web frameworks for a next project but if I run loadtest (for performance purpose) too many errors are fired. I create this repo for understand if is a issue on my side (that not appear with other web frameworks like 0http, koa, rayo, etc) or not. 

Steps to reproduce execute 'yarn start' (o 'yarn cluster') and in another terminal execute 'yarn load'. 
Can you give a look? Thanks in advance 🙏 

### Expected behavior/code

Don't fire so many errors 🤸‍♂️ 

### Environment

- Node/npm version: 14.5.0 / 6.14.5
- OS: Windows 10

**Comment by dalisoft** [comment]
Hi. see https://t.me/nanoexpress/18.
I am not maintaining this framework anymore.

Thanks for bug reporting

**Comment by dalisoft** [comment]
Hi @mrddter 

Sorry for delay.
Can you please describe issue more informative?
Project status is now **Active**, so bug can be fixed

**Comment by dalisoft** [comment]
@mrddter I got some time to get working on this project, seems your Minimal repo does not exist anymore. Can you create please another one?

**Comment by dalisoft** [comment]
No answers yet, issue will be closed until issue author wants fix after show
