### ISSUE TITLE
Imported modules do not work on ws handlers

### ISSUE THREAD

**Issue by kran6a** [nanoexpress/nanoexpress#70]
### Is you/your team sponsoring this project

- [ ] Yes
- [X] No

### Minimal reproducible repo

https://github.com/kran6a/nanoexpress-bug-2

### Current Behavior
Creating a websocket handler that needs to use imported dependencies causes the server to crash when a ws message is received by the server with a ReferenceError: <imported module name> is not defined.

I suspect the error is caused by an eval() or a Function constructor using the relative path of the imported module.

### Expected behavior/code

Using imported modules and constants on route handlers should work the same way it works on HTTP routes.

### Environment

- Node/npm version: Node 14.5.0/npm 6.14.5
- OS: Debian

**Comment by dalisoft** [comment]
Hi. see https://t.me/nanoexpress/18.
I am not maintaining this framework anymore, exactly i will add new features and quick bug fixes only for commercial users.

Thanks for bug reporting

**Comment by dalisoft** [comment]
@kran6a Sorry for delay, can you please describe issue more informative? Thanks

**Comment by dalisoft** [comment]
Hi, @kran6a
Good find, thanks for trying out nanoexpress. Fix soon will be released.
Have a nice day!

**Comment by dalisoft** [comment]
@kran6a 
Issue fixed, just use `nanoexpress` instead of `nanoexpress-pro` as now aliased
