### ISSUE TITLE
User forum

### ISSUE THREAD

**Issue by literakl** [nanoexpress/nanoexpress#81]
I try to find some resources on this interesting library without luck. Even StackOverflow is empty. The documentation is written for seasoned NodeJS developers and I, as a newbie, cannot even start the server from command line. Is there any forum? Thanks

**Comment by dalisoft** [comment]
Hi @literakl 
Thanks for interesting and trying out nanoexpress!

Currently, i think about how to make forum/discussion for nanoexpress, if there any suggestion about forum, i will try to-do.
About StackOverflow, there no posts due of this is relatively new framework and less users are using, so no posts yet on SO.

Maybe you can try create thread in Stackoverflow and post link here? i will try answer later.

**Comment by literakl** [comment]
It is there with new tag. Thanks.
https://stackoverflow.com/questions/60697934/failed-to-start-nanoexpress-server

**Comment by dalisoft** [comment]
Thanks, answered on StackOverflow

**Comment by literakl** [comment]
Another: https://stackoverflow.com/questions/60713009/body-parsing-does-not-work-in-nanoexpress
