### ISSUE TITLE
JSON body

### ISSUE THREAD

**Issue by literakl** [nanoexpress/nanoexpress#82]
Version 1.1.8

URL encoded www form data:

{"email":"literak@seznam.cz","password":"centrum"}: 

        console.log(req);

body: [Object: null prototype] {
    '{"email":"literak@seznam.cz","password":"centrum"}': ''
  }

Nanoexpress thinks that this is a key with empty value.

so this fails:

        const { email, password } = req.body;

**Comment by dalisoft** [comment]
Try latest version, should work. I fixed

**Comment by dalisoft** [comment]
I running `body-parser` example locally with some logging.

![Example](http://joxi.ru/8An7E1WC70w4Mr?d=1).

1. It works as expected including destructuring.
2. `[Object: null prototype]` - it's OK, but for now at least, this happens due of `querystring` `parse` function which does with `Object` something, but it's works same as `Object.

Try re-run or create minimal reproducible repository to debug.

Thanks for reporting bugs

**Comment by literakl** [comment]
JSON application type is parsed correctly, when I send the request from Postman, so you can close this issue. But I am stuck with frontend https://stackoverflow.com/questions/60763165/axios-post-stalled-in-chrome.

**Comment by literakl** [comment]
It is CORS issue. How can I write OPTIONS handler with empty body?

app.options('/v1/authorizeUser', async (req, res) => {
    console.log("OPTIONS authorizeUser");
    res.status(200);
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "POST, GET, OPTIONS, DELETE");
    return res;
});
