### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by literakl** [nanoexpress/nanoexpress#83]
I have a trouble with my POST JSON request: https://stackoverflow.com/questions/60763165/axios-post-stalled-in-chrome

It is CORS issue. How can I write OPTIONS handler with empty body? I tried this, but it did not help for chrome and it does not return anything to Postman until time out.

app.options('/v1/authorizeUser', async (req, res) => {
console.log("OPTIONS authorizeUser");
res.status(200);
res.setHeader("Access-Control-Allow-Origin", "*");
res.setHeader("Access-Control-Allow-Methods", "POST, GET, OPTIONS, DELETE");
return res;
});

I tried to use cors middleware but it had no effect

const cors = require('cors');

app.post('/v1/authorizeUser', cors(), async (req) => {
    console.log("POST authorizeUser");
    const { email, password } = req.body;
    console.log(email);
    return { status: 'Ok', body: req.body };
});

**Comment by m1k1o** [comment]
https://nanoexpress.js.org/testing/known-bugs#cors-per-route-bug

Add
```
app.options('/v1/authorizeUser', cors(), () => {});
```

**Comment by dalisoft** [comment]
Hi. 
This is known bug. On PRO version this issue is missing as i know. 

On free version only example like cors somehow works. 
I made PRO as recreated free version to support nanoexpress development. 

If you want get dedicated support, access to PRO version, please support project via becoming sponsor with Middle patron or higher.

**Comment by dalisoft** [comment]
@m1k1o Thanks a lot

**Comment by literakl** [comment]
Thank you. Would this design decision affect other middlewares as well?

**Comment by dalisoft** [comment]
Not always, but for some of them, yes. Like cors which uses `.options` method
