### ISSUE TITLE
Not found handler not activated 

### ISSUE THREAD

**Issue by literakl** [nanoexpress/nanoexpress#90]
I have defined both error and not found handler:

    app.setErrorHandler(
        (err, req, res) => {
            return res.send({
                status: 'error',
                status_code: 500,
                message: 'oops'
            })
        }
    );

    app.setNotFoundHandler((res, req) => {
        return res.send({ code: 404, message: 'You entered wrong url' });
    });

This is the handler:

    app.post('/bff/polls/:pollId/votes', auth.required, auth.cors, async (req, res) => { /* logic */});

I posted this URL:

http://127.0.0.1:3000/bff/polls/1e420fdqup/vote

And I received no response at all from server. There was a typo in URL, the correct address is:

http://127.0.0.1:3000/bff/polls/1e420fdqup/votes

It seems to be related to dynamic part of URL because I receive 404 error for this URL:

http://127.0.0.1:3000/v1/pols?obd=id&ps=10&lr=id:1e4h34qmef

with this handler:

    app.get('/bff/polls/last', auth.optional, async (req, res) => { /* logic */});

**Comment by dalisoft** [comment]
Hi @literakl 

Thanks for bug report. 
Is this behavior works in v1.x?
Can you create Minimal reproducible repo?
Can you create PR for fix this issue?

**Comment by literakl** [comment]
I tried here https://github.com/literakl/nano-options.git but I could not reproduce it today. Even my main code is working properly now. The only difference is that I restarted the server.

**Comment by dalisoft** [comment]
Nice to hear this good news

**Comment by literakl** [comment]
In fact this is bad news because the root cause was not found. The worst bugs are those not predictable, occuring from time to time.

**Comment by dalisoft** [comment]
I didn’t noticed the bug and didn’t appeared before, so i can fix only issues which can be reproduced
