### ISSUE TITLE
Question: No CommonJS for the simple version?

### ISSUE THREAD

**Issue by dnohr** [nanoexpress/nanoexpress#94]
Hi,

Any reason for not having CommonJS supported in the simple package? I think it would be easier to migrate from express if it's supported.

Thanks.

**Comment by dalisoft** [comment]
It is supported, exactly it is main file is CommonJS

**Comment by dalisoft** [comment]
See https://unpkg.com/browse/nanoexpress@2.0.1/package.json and auto-build this file https://unpkg.com/browse/nanoexpress@2.0.1/build/nanoexpress.js

**Comment by dalisoft** [comment]
Which error do you get when you want use as CommonJS?

**Comment by dnohr** [comment]
You're right, CommonJS is working on express, just didn't see any mention of it in the [documentation](https://nanoexpress.js.org/), which is why I asked.

Is serveStatic also part of the CommonJS? I'm getting following error when trying to include it:
_Error: Cannot find module 'nanoexpress/cjs/static'_
`const staticServe = require('nanoexpress/cjs/static');`

It's from following example:
https://nanoexpress.js.org/routes/static-serve

Thanks.

**Comment by dalisoft** [comment]
No, it’s not a part of cjs, it’s my typo in docs. I will fix as soon as i can get time

**Comment by dalisoft** [comment]
You trying to use syntax like PRO version, please see [this](https://github.com/nanoexpress/nanoexpress/blob/master/examples/static.js) example.
In simple version there `app.static` method. Easy and built-in
