### ISSUE TITLE
Websocket App publish crashes

### ISSUE THREAD

**Issue by joeyshipley** [nanoexpress/nanoexpress#99]
When attempting to call ``` app.publish('broadcast', 'test message'); ``` after the app.ws is setup causes the application to silently crash/die.

**Comment by joeyshipley** [comment]
Exploring this a bit, I found that updating nanoexpress.js in the const _app creation that updating the function setting seems to not crash this.

_app.publish = (channel, message) => app.publish(channel, message);

I am still having issues with my channels/subscriptions, so I'll keep poking at it before trying a PR out.

**Comment by joeyshipley** [comment]
After updating my local version to use the passthrough for the publish method, I was able to get it working without issue. I can provide code/examples if needed. 

If it helps, here's a PR > https://github.com/nanoexpress/nanoexpress/pull/100.

**Comment by dalisoft** [comment]
If possible, please, add example. 

Thanks

**Comment by joeyshipley** [comment]
Happy to. Thanks for addressing it so quickly. :)

https://github.com/joeyshipley/nanoexpress-publish

I have a local project that has a front end listening to the channel and it receives messages after the change. It's much larger though, not sure how to easily share end results past the server staying alive.

**Comment by dalisoft** [comment]
Issue not fixed, i got error

```bash
nanoexpress on  master [⇣] is 📦 v2.0.2 via ⬢ v13.14.0 
❯ NODE_ENV=development node examples/pub-sub.js 
  [nanoexpress:error] `cookie` was not found in your dependencies list, please install yourself for this feature working properly +0ms
  [nanoexpress:error] `cookie` was not found in your dependencies list, please install yourself for this feature working properly +2ms
  [nanoexpress:error] `fast-json-stringify` was not found in your dependencies list, please install yourself for this feature working properly +0ms
  [nanoexpress:log] [Server]: started successfully at [localhost:4000] in [7ms] +0ms
Sending publish/broadcast message to channel > my-channel
fish: 'NODE_ENV=development node examp…' terminated by signal SIGSEGV (Address boundary error)
nanoexpress on  master [!?] is 📦 v2.0.3 via ⬢ v13.14.0 
❯ bash

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ node -v
v13.14.0
bash-3.2$ NODE_ENV=development node examples/pub-sub.js 
  [nanoexpress:error] `cookie` was not found in your dependencies list, please install yourself for this feature working properly +0ms
  [nanoexpress:error] `cookie` was not found in your dependencies list, please install yourself for this feature working properly +2ms
  [nanoexpress:error] `fast-json-stringify` was not found in your dependencies list, please install yourself for this feature working properly +0ms
  [nanoexpress:log] [Server]: started successfully at [localhost:4000] in [5ms] +0ms
Sending publish/broadcast message to channel > my-channel
Segmentation fault: 11
bash-3.2$ NODE_ENV=development node --trace-uncaught examples/pub-sub.js 
  [nanoexpress:error] `cookie` was not found in your dependencies list, please install yourself for this feature working properly +0ms
  [nanoexpress:error] `cookie` was not found in your dependencies list, please install yourself for this feature working properly +2ms
  [nanoexpress:error] `fast-json-stringify` was not found in your dependencies list, please install yourself for this feature working properly +0ms
  [nanoexpress:log] [Server]: started successfully at [localhost:4000] in [4ms] +0ms
Sending publish/broadcast message to channel > my-channel
Segmentation fault: 11
bash-3.2$ npm outdated
^C
bash-3.2$ exit
exit
nanoexpress on  master [!?] is 📦 v2.0.3 via ⬢ v13.14.0 took 1m25s 
```

**Comment by joeyshipley** [comment]
Hrm, I'm still on LTS. I'll pull that node version and see on my end.

**Comment by joeyshipley** [comment]
I updated [example repo](https://github.com/joeyshipley/nanoexpress-publish) to specifically point to the patch, I forgot to do that earlier. I'll keep poking around, but if you could try that again it would be helpful.

**Comment by joeyshipley** [comment]
Sorry, I'm learning some of this. How did you pull down v2.0.3?

**Comment by dalisoft** [comment]
It’s locally, just increased patch number

**Comment by dalisoft** [comment]
LTS maintenance mode comes later as currently I don’t have enough time to migrate, move to separate branch

**Comment by dalisoft** [comment]
I catch another bug while testing recently, so much bugs and so less time

**Comment by joeyshipley** [comment]
Was thinking it might be a build/compile issue, but building from the fix repo keeps the code inline and worked for me again. Going to think about this and see if I can come up with a different direction to reproduce locally.

Do you have a different example, I can try that also if you do.

**Comment by dalisoft** [comment]
Please look at new branch [docs/example-pub-sub](https://github.com/nanoexpress/nanoexpress/blob/docs/example-pub-sub/examples/pub-sub.js), error while running as described [here](https://github.com/nanoexpress/nanoexpress/issues/99#issuecomment-625486908).

Can be run with this command `NODE_ENV=development node --trace-uncaught examples/pub-sub.js `

**Comment by joeyshipley** [comment]
Oh, good catch. I wouldn't have thought to throttle the memory and test it. At any rate, thanks for work on all of this.

**Comment by dalisoft** [comment]
Thank you for bug-report.
Of course, i didn't throttled memory, MS VSCode and Apple AppStore did it for me 😆
